### ISSUE TITLE
这个地址如何查看呢

### ISSUE THREAD

**Issue by xuewei1013** [JesseTzh/stable-diffusion-java#1]
gradio.live WebUI

**Comment by JesseTzh** [comment]
stable-diffusion-webui 项目启动时，在启动过程中控制台会输出地址，如果是本地/公网服务器项目也可以直接通过ip访问，代码仅为示例参考

**Comment by xuewei1013** [comment]
部署上去 一直报地址错误
Stable-Diffusion request error!
Exception in thread "main" com.jessetzh.handler.StableDiffusionException: Interface call error, please check if the URL is correct.
	at com.jessetzh.request.RequestExecutor.execute(RequestExecutor.java:36)
	at com.jessetzh.request.Text2Img.generate(Text2Img.java:24)
	at com.jessetzh.test.GeneratorTest.text2ImgText(GeneratorTest.java:42)
	at com.jessetzh.test.GeneratorTest.main(GeneratorTest.java:32)
